In [2]:
import numpy as np

decSecMat = [[8, 8, 7, 1, 7, 2, 2, 3, 5],
             [1, 8, 4, 4, 5, 2, 8, 1, 8],
             [4, 7, 3, 5, 2, 8, 7, 3, 2],
             [2, 1, 7, 6, 6, 4, 2, 5, 7],
             [6, 2, 3, 2, 3, 6, 7, 5, 4],
             [5, 6, 7, 7, 5, 3, 7, 2, 1],
             [2, 7, 5, 7, 3, 1, 6, 7, 4],
             [5, 1, 6, 5, 5, 5, 5, 3, 8]]

decSecMat = np.array(decSecMat)
body_bias = 1.2*((decSecMat-1)/8)
print(body_bias)

[[1.05 1.05 0.9  0.   0.9  0.15 0.15 0.3  0.6 ]
 [0.   1.05 0.45 0.45 0.6  0.15 1.05 0.   1.05]
 [0.45 0.9  0.3  0.6  0.15 1.05 0.9  0.3  0.15]
 [0.15 0.   0.9  0.75 0.75 0.45 0.15 0.6  0.9 ]
 [0.75 0.15 0.3  0.15 0.3  0.75 0.9  0.6  0.45]
 [0.6  0.75 0.9  0.9  0.6  0.3  0.9  0.15 0.  ]
 [0.15 0.9  0.6  0.9  0.3  0.   0.75 0.9  0.45]
 [0.6  0.   0.75 0.6  0.6  0.6  0.6  0.3  1.05]]
